# Generated by Django 3.2.25 on 2024-11-29 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='PetSightingPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('color', models.CharField(max_length=6)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_sightings/')),
                ('date_sighted', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=255)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=255)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sighting_posts', to='post.breed')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sighting_posts', to='post.species')),
            ],
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='LostPetPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('pet_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=6)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost_pets/')),
                ('date_lost', models.DateField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, default=None, max_digits=255, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, default=None, max_digits=255, null=True)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lost_posts', to='post.breed')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lost_posts', to='post.species')),
            ],
            bases=('post.post',),
        ),
    ]
