# Generated by Django 3.2.25 on 2024-11-30 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20241130_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpetpost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=None, max_digits=255, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=180), django.core.validators.MinValueValidator(limit_value=-180)]),
        ),
        migrations.AlterField(
            model_name='petsightingpost',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=255, validators=[django.core.validators.MaxValueValidator(limit_value=180), django.core.validators.MinValueValidator(limit_value=-180)]),
        ),
    ]
