# Generated by Django 3.2.25 on 2024-11-30 04:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20241130_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostpetpost',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='petsightingpost',
            name='photo',
        ),
        migrations.AlterField(
            model_name='petsightingpost',
            name='date_sighted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='PetPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=post.models.create_image_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
