# Generated by Django 3.2.25 on 2025-04-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20241130_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petphoto',
            options={'ordering': ['-id']},
        ),
    ]
