# Generated by Django 3.2.25 on 2024-11-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
