# Generated by Django 3.2.25 on 2025-05-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparticipation',
            name='score',
            field=models.FloatField(),
        ),
    ]
