# Generated by Django 3.2.25 on 2025-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
