# Generated by Django 3.2.25 on 2025-05-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_alter_testparticipation_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparticipation',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
