# Generated by Django 3.2.25 on 2025-05-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('trivia', '0003_alter_testparticipation_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('points', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
    ]
