# Generated by Django 3.2.25 on 2025-05-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
