# Generated by Django 3.2.25 on 2025-05-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_auto_20250530_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
